
name: wazo-webhookd-dedicated-exchange
namespace: wazocommunication
version: 1.0.0
author: Wazo authors
display_name: wazo-webhookd Dedicated Exchange
min_wazo_version: 24.01
tags:
  - wazo-webhookd
  - debug
homepage: https://github.com/wazo-communication/wazo-webhookd-dedicated-exchange
